apiVersion: apps/v1
kind: Deployment
metadata:
  name: gunicorn
spec:
  selector:
    matchLabels:
      stack: !Var djangoapp_name
      component: gunicorn
  template:
    metadata:
      labels:
        stack: !Var djangoapp_name
        component: gunicorn
    spec:
      enableServiceLinks: false
      securityContext: !Var gunicorn_pod_security_context
      # NOTE: No migrate in initContainer. In-memory sqlite migration handled by atlasso.apps:AtlassoAppConfig.
      containers:
        - name: gunicorn
          image: !Var djangoapp_image
          ports:
            - containerPort: 8000
          env: !Var gunicorn_environment
          securityContext: !Var gunicorn_container_security_context
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
              httpHeaders:
                - name: Host
                  value: !Var ingress_public_hostname
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
              httpHeaders:
                - name: Host
                  value: !Var ingress_public_hostname
            periodSeconds: 30
          volumeMounts:
            - mountPath: /tmp
              name: temp
      volumes:
        - name: temp
          emptyDir: {}