# djangoapp deployment using Kubernetes
# usage: emrichen -f default.vars.yaml kubernetes.in.yaml | kubectl apply -n djangoapp -f -


#########################
# GUNICORN (Web server) #
#########################
---
!Include gunicorn/service.in.yaml
---
!Include gunicorn/deployment.in.yaml
---
!If
  test: !Var djangoapp_secret_managed
  then: !Include gunicorn/secret.in.yaml


###########
# INGRESS #
###########
---
!Include ingress.in.yaml
